functionsDirectory = "/Users/alex.democskonyi/Downloads/rfp_search_app_bundle_copy/netlify/functions"
functionsDirectoryOrigin = "config-v1"
headers = []
redirects = []

[build]
publish = "/Users/alex.democskonyi/Downloads/rfp_search_app_bundle_copy"
publishOrigin = "config"
functions = "/Users/alex.democskonyi/Downloads/rfp_search_app_bundle_copy/netlify/functions"

[build.environment]

[build.processing]

[build.processing.css]

[build.processing.html]

[build.processing.images]

[build.processing.js]

[build.services]

[functions]

[functions."*"]

[[plugins]]
origin = "config"
package = "@netlify/plugin-functions-install-core"

[plugins.inputs]